test: test policy with APIM Gateway SDK
gravitee-io/gravitee-policy-override-http-method pull request #17
Opened 2022-05-25 08:30 UTC by ytvnr

**Issue**

https://github.com/gravitee-io/issues/issues/7745

2022-05-25 14:47 UTC, ThibaudAV requested changes

2022-05-25 14:47 UTC, ThibaudAV commented on pom.xml
> +        <gravitee-gateway-api.version>1.31.0</gravitee-gateway-api.version>
```suggestion
        <gravitee-gateway-api.version>1.32.2</gravitee-gateway-api.version>
```

2022-05-25 14:53 UTC, ThibaudAV approved these changes

2022-05-30 13:39 UTC, phiz71 approved these changes

2022-05-30 13:39 UTC, merged

2023-01-13 12:56 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0-alpha.1 :tada:

The release is available on:
- `2.0.0-alpha.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-override-http-method/releases/tag/2.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-17 14:50 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `2.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-override-http-method/releases/tag/2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: